### ISSUE TITLE
Nazwa assets występuje w hierarchii dwa razy

### ISSUE THREAD

**Issue by MarutanF** [MarutanF/ZPI-Spacerownik#38]
![image](https://user-images.githubusercontent.com/26172029/57780398-77928900-7728-11e9-8954-6d719bd2ff05.png)

Jako że assets w androidzie oznacza coś innego, to albo zmieniłabym nazwę, albo przeniosła IconFactory do utils.

**Comment by MalachowskiTomasz** [comment]
Utils oznaczają dodatkowe klasy, niezwiązane bezpośrednio z projektem, więc odpada.
Odnośnie nazwy, to proponuję debatę :)

**Comment by MalachowskiTomasz** [comment]
Daleko temu do issue, ale zmieniłem na "factories"
